### ISSUE TITLE
Looks like a class vs. is an autonomous object

### ISSUE THREAD

**Issue by szepeviktor** [shivapoudel/wp-plugin-starter#8]
Hello @shivapoudel!

Why is it popular in the WordPress ecosystem to write code in a class-like structure - e.g. Plugin.php - without the OOP data + code (object) structure?

WordPress is procedural, the hook system is procedural, themes are procedural.

What do you think about using namespaced functions?
There could be simple names such as `function start()` :)

**Comment by shivapoudel** [comment]
@szepeviktor There are different design patterns you will find for developing a WordPress plugin mostly. Among them depends on years of practice which to follow and it's never-ending. In my past 8+ years of experience, I have fought with different collisions and hence I decided to go with OOP and this seems very promising for me at least and my end-users.

If I am gonna explain why I choose it, what I have faced in the past years it will be a bit long and I prefer short writing. Besides this, the article was published by Steve Grunwell explaining [WordPress Plugins: Procedural or OOP?](https://stevegrunwell.com/blog/wordpress-plugin-design-patterns/) will answer all about choosing design patterns in the WordPress ecosystem so I can refer you to go for it, my friend :)

**Comment by szepeviktor** [comment]
Thank you for your response.

There is an ongoing [theoretical research](https://github.com/szepeviktor/small-project/issues/6) on main plugin file structure using only real objects where possible and namespaced functions for procedural things.

- Main plugin file: https://github.com/szepeviktor/small-project/blob/master/plugin-name.php
- Immutable configuration instead of global constant: `Config`
- Plugin requirements checker with fluid (builder) interface: `Requirements`
